stages:
  - build
  - push
  - deploy

variables:
  CONTAINER_IMAGE: $CI_REGISTRY_IMAGE
  DOCKER_DRIVER: overlay2
  DOCKER_CLI_EXPERIMENTAL: enabled
  #DOCKER_HOST: tcp://docker:2375
  #DOCKER_TLS_CERTDIR: ""
  DOCKER_HOST: tcp://docker:2376
  DOCKER_TLS_CERTDIR: "/certs"
  DOCKER_TLS_VERIFY: 1
  DOCKER_CERT_PATH: "$DOCKER_TLS_CERTDIR/client"
default:
  retry: 2
  image: registry.gitlab.com/adi90x/docker-buildx-qemu
  services:
    - docker:dind
  before_script:

    #- docker buildx inspect --bootstrap # Not need only for debug
    #- update-binfmts --enable # Important: Ensures execution of other binary formats is enabled in the kernel => Move to host setup
    # Set USE_CACHE=--no-cache if need to force rebuild

build-kaniko:
  stage: build
  image:
    name: gcr.io/kaniko-project/executor:debug
    entrypoint: [""]
  script:
    - mkdir -p /kaniko/.docker
    - echo "{\"auths\":{\"$CI_REGISTRY\":{\"auth\":\"$(echo -n ${CI_REGISTRY_USER}:${CI_REGISTRY_PASSWORD} | base64)\"}}}" > /kaniko/.docker/config.json
    - /kaniko/executor --context $CI_PROJECT_DIR --dockerfile $CI_PROJECT_DIR/Dockerfile --destination $CI_REGISTRY_IMAGE:kaniko


deploy-k3s:
  stage: deploy
  script:
    - mkdir -p ~/.kube/ && echo $KUBE_CONFIG_64 | base64 -d > ~/.kube/config
    - kubectl -n default rollout restart deploy/kube-active-proxy
