version: '2'
services:
  Proxy:
    image: adi90x/rancher-active-proxy
    environment:
      DEFAULT_HOST: "Default Domain ex: bar.com"
      DEFAULT_EMAIL: "Default Email ex: foo@bar.com"
    stdin_open: true
    volumes:
    - /local/path/data/nginx/htpasswd:/etc/nginx/htpasswd
    - /local/path/data/nginx/vhost.d:/etc/nginx/vhost.d
    - /local/path/data/nginx/letsencrypt:/etc/letsencrypt
    tty: true
    ports:
    - 80:80/tcp
    - 443:443/tcp
    labels:
      io.rancher.container.pull_image: always