#!/bin/bash

FORCE_KUBE_GEN_VERSION=""

version_available=$(curl --write-out %{http_code} --silent --output /dev/null https://gitlab.com/adi90x/kube-gen-KAP/builds/artifacts/$SOURCE_BRANCH/browse?job=compile-go)
if [ $version_available == "302" ]; then build_version=artifacts/$SOURCE_BRANCH; else build_version="artifacts/master"; fi
if [ $FORCE_KUBE_GEN_VERSION != "" ]; then build_version=$FORCE_KUBE_GEN_VERSION/artifacts; fi

docker build --build-arg VERSION_KUBE_GEN=$build_version -t $IMAGE_NAME .
